module.exports = {
  name: "Quickstart",
  isDefault: true,
  verboseLogging: false,
  randomizeMnemonicOnStart: false,
  logsDirectory: null,
  server: {
    hostname: "127.0.0.1",
    port: 7545,
    network_id: 5777,
    default_balance_ether: 100,
    total_accounts: 10,
    unlocked_accounts: [],
    locked: false,
    vmErrorsOnRPCResponse: true,
    logger: null,
    verbose: false,
    gasLimit: 6721975,
    gasPrice: 20000000000,
    hardfork: "muirGlacier",
    fork: null,
    fork_block_number: null
  },
  projects: [],
}