name: Release

# this should only run on release, but I'm triggering on pull_request so that I can test it
on: [pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node: [18.16.1]
        os: [windows-2019, ubuntu-18.04, macos-11]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Add msbuild to PATH
        # we need msbuild tools for the `bcrypto` module
        if: startsWith(matrix.os, 'windows-')
        uses: microsoft/setup-msbuild@v1.1
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.PAT}}
      - if: startsWith(matrix.os, 'windows-')
        run: |
          [Convert]::FromBase64String('${{ secrets.WINDOWS_CODE_SIGNING_PFX_BASE_64 }}') > certs/cert.pfx;
          Import-PfxCertificate -Password (ConvertTo-SecureString '${{ secrets.WINDOWS_CODE_SIGNING_PFX_PASSWORD }}' -AsPlainText -Force) -FilePath certs/cert.pfx -CertStoreLocation Cert:\CurrentUser\My > $null;
      - run: npm ci
        env:
          FORCE_COLOR: 1
      - if: startsWith(matrix.os, 'ubuntu-')
        run: npm run build-linux
      - if: startsWith(matrix.os, 'windows-')
        run: |
          [Convert]::FromBase64String('${{ secrets.WINDOWS_CODE_SIGNING_PFX_BASE_64 }}') | Out-File -FilePath .\cert.pfx;
          Import-PfxCertificate -Password (ConvertTo-SecureString '${{ secrets.WINDOWS_CODE_SIGNING_PFX_PASSWORD }}' -AsPlainText -Force) -FilePath .\cert.pfx -CertStoreLocation Cert:\CurrentUser\My > $null;
          npm run build-windows;
      - if: startsWith(matrix.os, 'macos-')
        run: npm run build-mac
      - uses: actions/upload-artifact@v3
        with:
          name: Release
          path: |
            dist/*.AppImage
            dist/*.dmg
            dist/*.blockmap
            dist/*.zip
            dist/*.appx
            dist/*.yml
